services:
  pneumo:
    image: pneumo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ENV=production
    networks:
      - pneumo_network
    entrypoint: ["./server"]

    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:8.1.3
    ports:
      - "6379:6379"
    networks:
      - pneumo_network

  astro:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - ./packages/web:/app
    ports:
      - "4321:4321"
      # bunx --bun astro dev
    command: sh -c "bun install && bunx --bun astro dev --host"
    networks:
      - pneumo_network


networks:
  pneumo_network:
    driver: bridge
